### ISSUE TITLE
Add tracking/monitoring

### ISSUE THREAD

**Issue by roknicmilos** [roknicmilos/portfolizer#45]
Check what DO provides out of the box first. 

- [x] Error reporting - Sentry
- [x] Visits (devices, frequency, etc.) - Google Analytics
- [ ] Performance (issues) - Prometeus with Graphana
- [x] Health check - Health checks, Uptime robot (monitoring service), Prometeus

**Comment by roknicmilos** [comment]
Prometheus + Grafan didn't work. Grafana Cloud wasn't showing any data. Digital Ocean dashboard and droplet resources overview is sufficient enough for now.
